POST http://localhost:4000/patients

Content-Type: application/json

{
  "name": "Umang",
  "email": "umang_with_billing@gmail.com",
  "address": "123 Ambedkar Road",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2024-11-28"
}